services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true         # DEV: dashboard en :8080
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.filepath=/logs/access.json
      - --metrics.prometheus=true
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.entryPoint=metrics
    ports:
      - "80:80"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/logs
    networks: [web]

  app:
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=PathPrefix(`/`)
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.services.app.loadbalancer.server.port=8000
    networks: [web]

networks:
  web: {}